title_primary: "纸蛇" # the bigger text
title_secondary: "Anything that can go wrong will go wrong." # the smaller text
hitokoto: 
    enable: true
    api: https://api.pka.moe/hitokoto/?format=js&charset=utf-8

keywords:

twitter: papersnake
rss: atom.xml
weibo: #username/id
instagram: #username
github: prnake

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.
valine: true
valine_appid: 'ufDJM5pqiTtGRDxfWK6SPs6K-gzGzoHsz'
valine_appkey: 'qwTff74RTdIHtaKOBRFWPIuU'

# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark

# 备案号
beian: '湘ICP备19014548号'

live2d: /live2d/remu/model.json